server:
  port: 8089
spring:
  application:
    name: student
  datasource:
    url: jdbc:mysql://localhost:3307/student
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client: # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    serviceUrl:
      defaultZone: http://localhost:8888/eureka ,http://localhost:8899/eureka